In [2]:
import numpy as np

In [5]:
last_rows = np.random.randn(1,1)
last_rows

array([[2.96337107]])

In [7]:
last_rows[-1:]

array([[2.96337107]])

In [9]:
np.random.randn(5,1).cumsum(axis=0)

array([[-0.09105457],
       [ 0.30759392],
       [-0.19792723],
       [-1.60453778],
       [-1.23442248]])

In [11]:
new_rows = last_rows[-1:] + np.random.randn(5,1).cumsum(axis=0)

In [12]:
new_rows

array([[ 1.94922115],
       [ 1.43281042],
       [ 1.84576763],
       [-0.21933112],
       [ 0.15513509]])